# Generated by Django 5.0.7 on 2024-07-11 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_app', models.BooleanField(default=False, verbose_name='Мобильное приложение')),
                ('delete_washorders', models.BooleanField(default=False, verbose_name='Может удалять заказы')),
                ('delete_employees', models.BooleanField(default=False, verbose_name='Может удалять сотрудников')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
