# Generated by Django 5.0.7 on 2024-07-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='delete_employees',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='delete_washorders',
        ),
    ]
